# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8086

spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: yy123456
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 1231eb07-5745-491a-aa24-946b092d683f
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO
#  global-config:
#   db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#      logic-delete-field: auto
#    header: token

logging:
  level:
    com.zyy.gulimall.produt.dao: debug


#seata:
#  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
#    type: nacos # 注册中心类型 nacos
#    nacos:
#      server-addr: localhost:8848 # nacos地址
#      namespace:       # namespace，默认为空
#      group: SEATA_GROUP # 分组，默认是SEATA_GROUP
#      application: seata-server # seata服务名称
#      username: nacos
#      password: nacos
#  tx-service-group: seata-demo # 事务组名称
#  service:
#    vgroup-mapping: # 事务组与cluster的映射关系
#      seata-demo: seata-server
#  data-source-proxy-mode: AT # 默认就是AT
