spring:
  cloud:
    gateway:
      routes:
#        - id: query_route
#          uri: https://www.baidu.com
#          predicates: #断言
#            - Query=url,baidu #如果前端的请求中带有baidu,那么就会跳转百度
#        - id: spring_route
#          uri: https://docs.spring.io/
#          predicates:
#            - Query=url,spring
#
        - id: qq_route
          uri: https://im.qq.com/index/
          predicates:
            - Query=url,qq

        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: coupon_route
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<segment>/?.*),/renren-fast/$\{segment}



    ribbon:
     nacos:
      enabled: false
    nacos:
      discovery:
        locator:
          enabled: true# 开启以应用名代理服务,即通过应用名称访问接口
        server-addr: 127.0.0.1:8848
        namespace: 1231eb07-5745-491a-aa24-946b092d683f
  application:
    name: gulimall-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_sms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: yy123456
server:
  port: 88